docker-deploy/web-app/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.contrib.auth.decorators import login_required
from . import views


app_name = "account"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/user_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('profile/',  login_required(views.UserView), name='profile'),
    path('signup/', views.signup, name='signup'),
    path('driver_register/', login_required(views.driver_reg),
         name='driver_register'),
    path('changeinfo/',  login_required(views.changeinfo), name='changeinfo'),
    path('delete_driver/',  login_required(views.deldriver), name='deldriver'),
]

docker-deploy/web-app/flashget/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('ride/', include('ride_service.urls')),
    path('account/', include('account.urls')),
    path('driver/', views.DriverView, name="driver"),
    path('orders/', views.OrdersView.as_view(template_name='orders.html'), name="orders"),
    path('trip/', views.TripView.as_view(template_name='trip.html'), name="trip"),
]

docker-deploy/web-app/flashget/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'index.html')


@login_required(login_url='/account/login')
def DriverView(request):
    if request.user.is_driver == 0:
        return redirect(to='/account/driver_register')
    return render(request, 'driver.html')


class OrdersView(LoginRequiredMixin, TemplateView):
    template_name = 'orders.html'


class TripView(LoginRequiredMixin, TemplateView):
    template_name = 'trip.html'

docker-deploy/web-app/flashget/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
	<style type="text/css">
	translate(-50%,-50%);
    background-color: #2a9d8f;
}
.progress{
    position: relative;
    height: 10px;
    width: 1110%;
    border: 10px solid #f4a261;
    border-radius: 15px;
}
.progress .color{
    position: absolute;
    background-color: #ffffff;
    width: 0px;
    height: 10px;
    border-radius: 15px;
    animation: progres 4s infinite linear;
}
@keyframes progres{
    0%{
      width: 0%;
    }
    25%{
        width: 50%;
    }
    50%{
        width: 75%;
    }
    75%{
        width: 85%;
    }
    100%{
        width: 100%;
    }
};





         body {
             font-family: 'lato', sans-serif;
        }
         .container {
             max-width: 1000px;
             margin-left: auto;
             margin-right: auto;
             padding-left: 10px;
             padding-right: 10px;
        }
         h2 {
             font-size: 26px;
             margin: 20px 0;
             text-align: center;
        }
         h2 small {
             font-size: 0.5em;
        }
         .responsive-table li {
             border-radius: 3px;
             padding: 25px 30px;
             display: flex;
             justify-content: space-between;
             margin-bottom: 25px;
        }
         .responsive-table .table-header {
             background-color: #95a5a6;
             font-size: 14px;
             text-transform: uppercase;
             letter-spacing: 0.03em;
        }
         .responsive-table .table-row {
             background-color: #fff;
             box-shadow: 0px 0px 9px 0px rgba(0, 0, 0, 0.1);
        }
         .responsive-table .col-1 {
             flex-basis: 25%;
        }
         .responsive-table .col-2 {
             flex-basis: 25%;
        }
         .responsive-table .col-3 {
             flex-basis: 25%;
        }
         .responsive-table .col-4 {
             flex-basis: 25%;
        }
         @media all and (max-width: 767px) {
             .responsive-table .table-header {
                 display: none;
            }
             .responsive-table li {
                 display: block;
            }
             .responsive-table .col {
                 flex-basis: 100%;
            }
             .responsive-table .col {
                 display: flex;
                 padding: 10px 0;
            }
             .responsive-table .col:before {
                 color: #6c7a89;
                 padding-right: 10px;
                 content: attr(data-label);
                 flex-basis: 50%;
                 text-align: right;
            }
        }


</style>
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        {%block content%}{%endblock%}
    </main>
</body>

</html>

docker-deploy/web-app/flashget/templates/driver.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>
    Template Driver
</h1>
{% endblock %}

docker-deploy/web-app/flashget/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Welcome!</h1>
  <p class="w3-xlarge">Need a Ride?</p>
  <button class="w3-button w3-black w3-padding-large w3-large w3-margin-top" onclick="location.href = 'ride/service';">Flashget!</button>
</header>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h1>Our Motto</h1>
      <h5 class="w3-padding-32">Fast, Secure, Reliable!</h5>

      <p class="w3-text-grey">Flashget is cool, Flashget is good. Use Flashget!</p>
    </div>

    <div class="w3-third w3-center">
      <i class="fa fa-anchor w3-padding-64 w3-text-red"></i>
    </div>
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-center">
      <i class="fa fa-coffee w3-padding-64 w3-text-red w3-margin-right"></i>
    </div>

    <div class="w3-twothird">
      <h1>Our Promise</h1>
      <h5 class="w3-padding-32">Cheap and Reliable delivery!</h5>

      <p class="w3-text-grey">With each ride starting from $2.50, everyone can afford a ride! You won't get jumped by the driver, we promise!</p>
    </div>
  </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>
 <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>
{% endblock %}

docker-deploy/web-app/flashget/templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{%url 'index'%}">Home</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{%url 'user_search'%}">Start/Join Ride<span class="sr-only">(current)</span></a></li>
          <li><a href="{%url 'driver_search'%}">Take Order</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi {{user.name}}!<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'account:profile' %}">User Profile</a></li>
                  <li><a href="{% url 'user_history' %}">User History</a></li>
                  <li><a href="{% url 'driver_history' %}">Driver History</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'account:logout' %}">Log out</a></li>
                </ul>
              </li>
            {% else %}
          <li><a href="{% url 'account:login' %}">Login</a></li>
          <li><a href="{% url 'account:signup' %}">Register</a></li>
          {% endif %}
          
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

docker-deploy/web-app/flashget/templates/orders.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>
    Template Orders
</h1>
{% endblock %}

docker-deploy/web-app/flashget/templates/trip.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>
    Template Trip
</h1>
{% endblock %}